import os
import sys

FORBIDDEN_STRINGS = [
    "AurumShield",
    "AURUMSHIELD",
    "Sovereign-Grade",
    "Daubert-compliant",
    "court-admissible",
    "allow_origin_regex",
    "Create Next App",
    "Generated by create next app",
    "SuperSecretPassword123",
    "ungated MOCK_ENCRYPTED_PACKET"
]

def scan_directory(directory: str) -> bool:
    failed = False
    for root, _, files in os.walk(directory):
        if "node_modules" in root or ".next" in root or "__pycache__" in root or ".git" in root:
            continue
        for file in files:
            if not (file.endswith(".ts") or file.endswith(".tsx") or file.endswith(".py") or file.endswith(".md")):
                continue
            if file == "check_forbidden_strings.py":
                continue
            path = os.path.join(root, file)
            with open(path, "r", encoding="utf-8") as f:
                try:
                    content = f.read()
                    for f_str in FORBIDDEN_STRINGS:
                        if f_str in content:
                            print(f"FORBIDDEN STRING '{f_str}' FOUND IN: {path}")
                            failed = True
                except UnicodeDecodeError:
                    pass
    return failed

if __name__ == "__main__":
    failed = False
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    
    # We only scan these critical areas to prevent brand regression
    target_dirs = [
        os.path.join(base_dir, "frontend", "app"),
        os.path.join(base_dir, "frontend", "components"),
        os.path.join(base_dir, "backend"),
        os.path.join(base_dir, "scripts")
    ]
    
    for d in target_dirs:
        if os.path.exists(d):
            if scan_directory(d):
                failed = True
                
    if failed:
        print("ERROR: CI Guardrail checks failed. Forbidden strings detected.")
        sys.exit(1)
        
    print("SUCCESS: Guardrail checks passed.")
    sys.exit(0)
